config/routes.rb
Rails.application.routes.draw do
  root to: "visitors#index"
  devise_for :users
  resources :events
  resource :shopping_cart
  resource :subscription_cart
  resources :payments
  resources :plans
  resources :subscriptions

  get "paypal/approved", to: "pay_pal_payments#approved"
  post "stripe/webhook", to: "stripe_webhook#action"
end

app/models/shopping_cart.rb
class ShoppingCart
  attr_accessor :user

  def initialize(user)
    @user = user
  end

  def tickets
    @tickets ||= user.tickets_in_cart
  end

  def events
    tickets.map(&:event).uniq!.sort_by!(&:name)
  end

  def tickets_by_performance
    tickets.group_by { |t| t.performance.id }
  end

  def performance_count
    tickets_by_performance.each_pair.each_with_object({}) do |pair, result|
      result[pair.first] = pair.last.size
    end
  end

  def performances_for(event)
    tickets.map(&:performance)
           .select { |performance| performance.event == event }
           .uniq!
           .sort_by!(&:start_time)
  end

  def subtotal_for(performance)
    tickets_by_performance[performance.id].sum(&:price)
  end

  def total_cost
    tickets.map(&:price).sum
  end

  def item_attribute
    :ticket_ids
  end

  def item_ids
    tickets.map(&:id)
  end
end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController
  def show
    @cart = ShoppingCart.new(current_user)
  end

  def update
    performance = Performance.find(params[:performance_id])
    workflow = AddsToCart.new(
      user: current_user, performance: performance,
      count: params[:ticket_count].to_i
    )
    workflow.run

    if workflow.success
      redirect_to shopping_cart_path
    else
      redirect_to performance.event
    end
  end
end

app/views/shopping_carts/_credit_card_info.html.slim
h3 Payment Options

= form_tag(payments_path,
  class: "credit-card-form form-horizontal", id: "payment-form") do

  = hidden_field_tag(:purchase_amount_cents, @cart.total_cost.cents)
  = hidden_field_tag(@cart.item_attribute, @cart.item_ids)
  = hidden_field_tag(:purchase_type, @cart.class.name)
  = hidden_field_tag(:stripe_token, "", id: "spec_stripe_token")

  .paypal
    img(src="https://www.paypal.com/en_US/i/logo/PayPal_mark_37x23.gif"
      align="left" style="margin-right:7px;")
    span(style="font-size:11px; font-family: Arial, Verdana")
      | The safer, easier way to pay.
    = radio_button_tag(:payment_type,
      :paypal, false,
      class: "payment-type-radio", id: "paypal_radio")
  .credit_card
    | Credit Card
    = radio_button_tag(:payment_type,
      :credit, true,
      class: "payment-type-radio", id: "credit_radio")

  .bg-danger#error-text

  #credit-card-info
    h3 Credit Card Info
    .row
      .form-group
        .col-sm-2
          = label_tag(:credit_card_number, "Credit Card Number",
            class: "control-label")
        .col-sm-3
          input.form-control.valid-field(data-stripe="number"
            id="credit_card_number")
        .col-sm-1
          = image_tag("creditcards/credit.png", id: "card-image")

    .row
      .form-group
        .col-sm-2
          = label_tag(:expiration_month, "Month", class: "control-label")
        .col-sm-2
          input.form-control.valid-field(placeholder="MM / YY"
            data-stripe="exp" id="expiration_date")

    .row
      .form-group
        .col-sm-2
          = label_tag(:cvc, "CVC", class: "control-label")
        .col-sm-1
          input.form-control.valid-field(data-stripe="cvc" id="cvc")

  .row
    .form-group
      .col-sm-3
        = submit_tag("Purchase Cart", class: "btn btn-default", id: "purchase")

app/views/shopping_carts/show.html.slim
h1 Shopping Cart

- @cart.events.each do |event|
  h2= event.name
  div(id=dom_id(event))
    table.table
      thead
        th Date
        th Tickets
        th Total Price
      tbody
        - @cart.performances_for(event).each do |performance|
          tr(id=dom_id(performance))
            td= performance.start_time.to_date.to_s(:long)
            td.ticket_count= @cart.performance_count[performance.id]
            td.subtotal
              = humanized_money_with_symbol(@cart.subtotal_for(performance))

h3 Total #{humanized_money_with_symbol(@cart.total_cost)}

h2 Checkout

= render "credit_card_info"