config/routes.rb
Rails.application.routes.draw do
  root to: "visitors#index"
  devise_for :users
  resources :events
  resource :shopping_cart
  resource :subscription_cart
  resources :payments
  resources :plans
  resources :subscriptions

  get "paypal/approved", to: "pay_pal_payments#approved"
  post "stripe/webhook", to: "stripe_webhook#action"
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :performances, dependent: :destroy
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.html.slim
h2 Upcoming Performances
- @events.each do |event|
  h2= link_to(event.name, event_path(event))

app/views/events/show.html.slim
h1= @event.name

h2 Available Performances
- @event.performances.each do |performance|
  div(id=dom_id(performance))
    .row
      = form_tag(shopping_cart_path, method: :patch) do
        = hidden_field_tag("performance_id", performance.id)
        .col-md-2
          h4= performance.start_time.to_date.to_s(:long)
        .col-md-1
          .form-group
            = select_tag("ticket_count",
              options_for_select((1..10).to_a), class: "form-control")
        .col-md-3
          .form-group
            = submit_tag("Add to Cart",
              class: "btn btn-primary", id: "add-to-cart")