config/routes.rb
Rails.application.routes.draw do
  root to: "visitors#index"
  devise_for :users
  resources :events
  resource :shopping_cart
  resource :subscription_cart
  resources :payments
  resources :plans
  resources :subscriptions

  get "paypal/approved", to: "pay_pal_payments#approved"
  post "stripe/webhook", to: "stripe_webhook#action"
end

app/views/layouts/_messages.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
    .alert(class="alert-#{name.to_s == "notice" ? "success" : "danger"}")
      button.close(
        type="button" data-dismiss="alert" aria-hidden="true") &times;
      div(id="flash_#{name}")= msg

app/views/layouts/_navigation.html.slim
nav.navbar.navbar-default.navbar-static-top
  .container
    .navbar-header
      button.navbar-toggle(
        data-target=".navbar-collapse" data-toggle="collapse")
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
    = link_to("Snow Globe Theater", root_path, class: "navbar-brand")
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        = render "layouts/navigation_links"

app/views/layouts/_navigation_links.html.slim
li= link_to("Events", events_path)
- if user_signed_in?
  li= link_to("Edit account", edit_user_registration_path)
  li= link_to("Sign out", destroy_user_session_path, method: "delete")
- else
  li= link_to("Sign in", new_user_session_path)
  li= link_to("Sign up", new_user_registration_path)

app/views/layouts/application.html.slim
doctype html
html(lang="en")
  head
    meta(charset="utf-8")
    meta(name="viewport" content="width=device-width, initial-scale=1.0")
    title= content_for?(:title) ? yield(:title) : "Snow Globe Theater"
    meta(name="description"
      content="#{content_for?(:description) ? yield(:description) : "Globe"}")
    / START: code.add_stripe
    = stylesheet_link_tag("application",
      media: "all", "data-turbolinks-track" => true)
    = javascript_include_tag("#{STRIPE_JS_HOST}/v2/#{STRIPE_JS_FILE}")
    = javascript_include_tag("application", "data-turbolinks-track" => true)

    javascript:
      Stripe.setPublishableKey(
        "#{Rails.application.credentials.stripe[:publishable_key]}");
    / END: code.add_stripe
    = stylesheet_link_tag("application",
      media: "all", "data-turbolinks-track" => true)
    = javascript_include_tag("application", "data-turbolinks-track" => true)
    = csrf_meta_tags

  body
    header
      = render "layouts/navigation"
    main(role="main")
      .container
        = render "layouts/messages"
        = yield